# 默认开启暗色主题
dark = false
author = 'spacetraveler'
slogan = 'Life is interesting.'  # 'Life is just a joker.'
startDate = 2016                 # 'Copyright © 2016 - now'

# 激活页面加载时的过渡动画
hasActiveAnimate = true

# 激活页面浮动盒子动画
# hasActiveFloatingBox = true

# 文章页是否显示其相关系列文章（页面左侧区域）
isShowRelativePosts = true

# 导航页右侧是否显示迷你必应搜索
isShowMinishipBoxOfNav = true

# 导航页是否显示顶部搜索区域
isShowShipBoxOfNav = true

# 导航页是否显示站内搜索（站内文章内容检索）
# isShowLocalSearch = true

# 导航页是否显示最近文章列表
isShowRecentPostsOfNav = true

# 激活 cool 模式，酷爽但是消耗资源也更多，
# 浏览器有缓存，更换后强制页面刷新（快捷键为 Ctrl+Shift+R）一下或重启本地服务即可，
# ------------------
# <更新> 现在可以直接在这里修改背景壁纸并调整壁纸遮罩透明度
# - coolBackground 文件位于 `/static/imgs/bg` 文件夹中，默认为 `default.jpg`
# - coolOpacity 默认为 0.81 ，背景色彩透明度，在 0 ~ 1 之间
# - coolSaturate 默认为 180% ，背景色彩饱和度，在 0% ~ 200% 之间
# - coolBlur 默认为 6px ，背景色彩模糊度，数值越大越模糊
# hasActiveCool = true
coolBackground = 'color.jpg'
coolOpacity = 0.69 # 0.86
coolSaturate = '180%'
coolBlur = '6px'

# 首页图片/文字
[params.img]
	# 内置默认为 `cat.svg ……`，当然你可以
	# 把自己喜欢图片放在 `static/imgs/` 目录中，并在 `src` 引用它,
	# ❌ 你还可以通过 `width` 调整引入图片的显示大小，
	# ❌ 如果，将 `width` 设置为 '' 或 0 ，
	# ❌ 将默认使用图片自身分辨率尺寸
	# ❌ width = 90
	# 🔔 图标用途发生变化，不再支持此处设置尺寸，但
	# 新增支持设置背景色，
	# 将 background 设置为 ''，默认为 `#000`
	# ！ 为保证显示效果，建议选用 1：1 比例图片
	# src = 'cat.svg'
	src = 'Kowalski.jpg'
	background = '#0003'
	# 为该图片附加一个点击链接功能，缺省为 `/about`，当然
	# 你也可以定义为任何你相要的超链接
	link = '/about'

[params.contact]
	# icp = ''                                    # 备案号，如果你不想显示，设置为 '' 空即可
	# icplink = ''                                # 备案链接
	# beian = ''                                  # 公安备案，如果你不想显示，设置为 '' 空即可
	# beiancode = ''                              # 公安备案识别码
	github_user = 'spacetravelerlyl'            # Github 用户名，导航页 github 小组件使用
	email = 'spacetraveler.lyl@gmail.com'
	github = 'https://github.com/loveminimal'	
	# wechat = 'imgs/bg/wechat.jpg'             # 微信二维码地址
	# weibo = 'https://weibo.com/u/6867589681'
	# zhihu = 'https://www.zhihu.com/people/loveminimal'
	# jianshu = 'https://www.jianshu.com/u/eebcc2974936'
	# bilibili = 'https://space.bilibili.com/11608450'
	# douyin = 'https://www.douyin.com/user/self'
	# xiaohongshu = 'https://www.xiaohongshu.com/user/profile/60004c750000000001002065'
	# reddit = 'https://www.reddit.com/user/aituyaa'
	# twitter = 'https://twitter.com/aituyaa'
	# mastodon = 'https://mastodon.social/@loveminimal'
	# instagram = 'https://www.instagram.com/loveminimal163'
	# youtube = 'https://www.youtube.com/@aituyaa'
	# telegram = 'https://web.telegram.org/k/#@aituyaa'	# 'https://t.me/aituyaa'
	# discord = 'https://discord.com/channels/@me'

	[params.contact.config]
		color = '#696969'                         # 图标颜色，默认为浅灰色
		slogan = ''                               # 联系标语，不想显示，可以置空
		# isShowNavLink = true                     # 是否在联系栏左侧显示快捷导航链接（PS：站点首页总会显示）
		target = '_self'                          # 定义左侧快捷导航链接打开方式，_blank 在新标签页 _self 在当前标签页
		ship = ''                                 # 联系栏 icon ，允许自定义该图标链接（/ship 为外链的个人定制化搜索页）；隐藏，设置为 '' 空即可

# https://utteranc.es/
# 在开发环境下（http://localhost:1313/），不再启用评论插件，
# 如果想在开发环境下启用它，修改服务端口即可，如下
# hugo server -p=1314
[params.utterances]
	active = false                            # 是否启用评论插件
	repo = "loveminimal/comment"              # 输入你的仓库名称
	issueTerm = "pathname"
	theme = "github-light"
	crossorigin = "anonymous"

# 在开发环境下（http://localhost:1313/），不再启用评论插件，
# 如果想在开发环境下启用它，修改服务端口即可，如下
# hugo server -p=1314
# ---------
# 在 https://giscus.app/ 中，选择配置后会自动生成，如 data-*
# 默认开启 data-loading="lazy"
[params.giscus]
	active = true                             # 是否启用评论插件
	repo = "loveminimal/comment"              # 输入你的仓库名称,???????
	repoId = "R_kgDOJNJQ8g"                   # ??????????
	category="General"
	categoryId="DIC_kwDOJNJQ8s4CYl0m"
	mapping = "title"
	inputPosition = "bottom"
	theme = "noborder_light"
	crossorigin = "anonymous"
	lang = "zh-CN"